run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
    - text: "Error return value is not checked"
      linters:
        - errcheck
    - text: "is unused"
      linters:
        - unused
  max-issues-per-linter: 50
  max-same-issues: 10
