#!/usr/bin/env python3
import sys
if len(sys.argv) != 4 or sys.argv[2] != 'com' or sys.argv[3] != 'TestFuncionou':
    print('Uso: crie <arquivo> com TestFuncionou')
    sys.exit(1)
with open(sys.argv[1], 'w', encoding='utf-8') as f:
    f.write('TestFuncionou')
